// ─────────────────────────────────────────────────────────────────────────────
// generateReport.ts  –  PDF & TXT report generators
// No third-party dependencies — uses browser print API for PDF,
// Blob/anchor trick for TXT. Works in any modern browser.
// ─────────────────────────────────────────────────────────────────────────────

import {
  COMPANY_LOGO_PATH,
  CONDUCTORS,
  DATASET_INFO,
  DATASET_NAME,
  ENGINE_VERSION,
  NETWORK_SUMMARY,
  POLES,
  SPANS,
} from "./reportData";

// ─── helpers ─────────────────────────────────────────────────────────────────

function nowString() {
  return new Date().toLocaleString("en-IN", {
    day: "2-digit", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit", second: "2-digit",
    hour12: true,
  });
}

function statusColor(status: string) {
  if (status === "critical") return "#c0392b";
  if (status === "warning")  return "#e67e22";
  return "#27ae60";
}

function sagColor(sag: number) {
  if (sag > 2)   return "#c0392b";
  if (sag > 1.5) return "#e67e22";
  return "#27ae60";
}

function lossColor(loss: number) {
  if (loss > 3)   return "#c0392b";
  if (loss > 1.5) return "#e67e22";
  return "#1a5276";
}

// ─── shared HTML header & footer ────────────────────────────────────────────

function htmlHeader(reportTitle: string, logoDataUrl: string) {
  return `
    <div style="display:flex;align-items:center;gap:24px;padding-bottom:16px;
                border-bottom:3px solid #1a3a5c;margin-bottom:24px;">
      ${logoDataUrl
        ? `<img src="${logoDataUrl}" alt="Company Logo"
               style="height:56px;object-fit:contain;flex-shrink:0;" />`
        : `<div style="width:56px;height:56px;background:#1a3a5c;border-radius:8px;
                       display:flex;align-items:center;justify-content:center;
                       color:white;font-weight:700;font-size:18px;">GS</div>`
      }
      <div style="flex:1;">
        <div style="font-size:11px;color:#5d6d7e;letter-spacing:2px;
                    text-transform:uppercase;font-weight:600;">
          GridScan LiDAR Powerline Analytics Platform
        </div>
        <div style="font-size:22px;font-weight:700;color:#1a3a5c;
                    margin-top:4px;line-height:1.2;">
          ${reportTitle}
        </div>
      </div>
      <div style="text-align:right;font-size:11px;color:#5d6d7e;line-height:1.8;">
        <div><strong>Dataset:</strong> ${DATASET_NAME}</div>
        <div><strong>Info:</strong> ${DATASET_INFO}</div>
        <div><strong>Generated:</strong> ${nowString()}</div>
        <div><strong>Engine:</strong> ${ENGINE_VERSION}</div>
      </div>
    </div>`;
}

function htmlFooter(pageLabel = "") {
  return `
    <div style="margin-top:40px;padding-top:12px;border-top:1px solid #d5d8dc;
                display:flex;justify-content:space-between;font-size:10px;
                color:#7f8c8d;page-break-inside:avoid;">
      <span>Generated by GridScan LiDAR Powerline Analytics Platform</span>
      <span style="color:#1a3a5c;font-weight:600;">CONFIDENTIAL ENGINEERING REPORT</span>
      <span>${pageLabel}</span>
    </div>`;
}

// ─── section heading ─────────────────────────────────────────────────────────

function sectionHeading(title: string) {
  return `
    <div style="background:#1a3a5c;color:white;padding:8px 14px;
                border-radius:6px;font-size:13px;font-weight:700;
                letter-spacing:1px;margin:20px 0 12px;
                text-transform:uppercase;">
      ${title}
    </div>`;
}

// ─── table helpers ────────────────────────────────────────────────────────────

function tableHead(...cols: string[]) {
  return `<thead><tr>${cols.map((c) =>
    `<th style="background:#1a3a5c;color:white;padding:8px 12px;
               text-align:left;font-size:11px;font-weight:600;
               letter-spacing:0.5px;white-space:nowrap;">${c}</th>`
  ).join("")}</tr></thead>`;
}

function tableRow(cells: string[], shade: boolean) {
  const bg = shade ? "#eaf0fb" : "#ffffff";
  return `<tr style="background:${bg};">${cells.map((c) =>
    `<td style="padding:7px 12px;font-size:12px;border-bottom:1px solid #d5d8dc;">${c}</td>`
  ).join("")}</tr>`;
}

function table(head: string, rows: string) {
  return `
    <table style="width:100%;border-collapse:collapse;margin-bottom:16px;
                  box-shadow:0 1px 4px rgba(0,0,0,0.08);">
      ${head}
      <tbody>${rows}</tbody>
    </table>`;
}

// ─── KPI row ─────────────────────────────────────────────────────────────────

function kpiGrid(items: { label: string; value: string; sub?: string }[]) {
  return `
    <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));
                gap:12px;margin:16px 0;">
      ${items.map((k) => `
        <div style="background:#eaf0fb;border:1px solid #aed6f1;border-radius:8px;
                    padding:12px;text-align:center;">
          <div style="font-size:10px;color:#5d6d7e;text-transform:uppercase;
                      letter-spacing:1px;font-weight:600;">${k.label}</div>
          <div style="font-size:20px;font-weight:700;color:#1a3a5c;margin-top:4px;">
            ${k.value}
          </div>
          ${k.sub ? `<div style="font-size:10px;color:#7f8c8d;margin-top:2px;">${k.sub}</div>` : ""}
        </div>`
      ).join("")}
    </div>`;
}

// ─── base print wrapper ──────────────────────────────────────────────────────

function printWindow(bodyHtml: string, filename: string) {
  const win = window.open("", "_blank", "width=900,height=700");
  if (!win) {
    alert("Pop-up blocked. Please allow pop-ups for this site and try again.");
    return;
  }
  win.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>${filename}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      color: #2c3e50;
      background: #ffffff;
      padding: 32px 36px;
      font-size: 13px;
      line-height: 1.5;
    }
    @media print {
      body { padding: 20px 24px; }
      @page { margin: 16mm 14mm; size: A4; }
    }
    h2 { color: #1a3a5c; margin: 16px 0 8px; }
    p  { margin-bottom: 8px; }
  </style>
</head>
<body>
${bodyHtml}
</body>
</html>`);
  win.document.close();
  win.focus();
  setTimeout(() => {
    win.print();
    // On most browsers print dialog includes "Save as PDF"
  }, 600);
}

// ─── load logo as base64 data URL ────────────────────────────────────────────

async function loadLogoDataUrl(): Promise<string> {
  try {
    const res = await fetch(COMPANY_LOGO_PATH);
    if (!res.ok) return "";
    const blob = await res.blob();
    return await new Promise<string>((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => resolve("");
      reader.readAsDataURL(blob);
    });
  } catch {
    return "";
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. ASSET INVENTORY REPORT
// ─────────────────────────────────────────────────────────────────────────────

export async function generateAssetInventoryReport() {
  const logo = await loadLogoDataUrl();
  const avgH = NETWORK_SUMMARY.avgPoleHeight;

  const poleRows = POLES.map((p, i) =>
    tableRow([
      `<strong>Pole ${p.id}</strong>`,
      `${p.height.toFixed(2)} m`,
      `${p.x.toFixed(1)}`,
      `${p.y.toFixed(1)}`,
      p.height === Math.max(...POLES.map((x) => x.height))
        ? `<span style="color:#c0392b;font-weight:700;">MAX ★</span>`
        : `<span style="color:#27ae60;">Normal</span>`,
    ], i % 2 === 1)
  ).join("");

  const conductorRows = CONDUCTORS.map((c, i) =>
    tableRow([
      `<strong>${c.id}</strong>`,
      `Span ${c.span}`,
      `<span style="color:${c.type === "Upper" ? "#1a5276" : "#6c3483"};font-weight:600;">${c.type}</span>`,
      `${c.length.toFixed(2)} m`,
      `<span style="color:${sagColor(c.sag)};font-weight:600;">${c.sag.toFixed(2)} m</span>`,
      "Class 21",
    ], i % 2 === 1)
  ).join("");

  const body = `
    ${htmlHeader("Asset Inventory Report", logo)}
    ${kpiGrid([
      { label: "Total Poles", value: String(NETWORK_SUMMARY.totalPoles), sub: "detected" },
      { label: "Total Conductors", value: String(NETWORK_SUMMARY.totalConductors), sub: "wires" },
      { label: "Avg Pole Height", value: `${avgH} m`, sub: "network avg" },
      { label: "Total Spans", value: String(NETWORK_SUMMARY.totalSpans), sub: "spans" },
    ])}
    ${sectionHeading("Utility Pole Registry")}
    ${table(tableHead("Pole ID","Height (m)","X Coord","Y Coord","Status"), poleRows)}
    ${sectionHeading("Conductor Registry")}
    ${table(tableHead("Conductor ID","Span","Type","Wire Length","Sag","Class"), conductorRows)}
    ${htmlFooter()}`;

  printWindow(body, "Asset_Inventory_Report");
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. SPAN ANALYTICS REPORT
// ─────────────────────────────────────────────────────────────────────────────

export async function generateSpanAnalyticsReport() {
  const logo = await loadLogoDataUrl();
  const avgSag = NETWORK_SUMMARY.avgSag;
  const maxSag = NETWORK_SUMMARY.maxSag;

  const spanRows = SPANS.flatMap((s, i) => [
    tableRow([
      `<strong>${s.id} U</strong>`,
      "Upper",
      `${s.poleSpan.toFixed(2)} m`,
      `${s.upperLength.toFixed(2)} m`,
      `<span style="color:${sagColor(s.upperSag)};font-weight:600;">${s.upperSag.toFixed(2)} m</span>`,
      `+${(s.upperLength - s.poleSpan).toFixed(2)} m`,
      `<span style="color:${statusColor(s.status)};font-weight:600;text-transform:uppercase;">${s.status}</span>`,
    ], i % 2 === 0),
    tableRow([
      `<strong>${s.id} L</strong>`,
      "Lower",
      `${s.poleSpan.toFixed(2)} m`,
      `${s.lowerLength.toFixed(2)} m`,
      `<span style="color:${sagColor(s.lowerSag)};font-weight:600;">${s.lowerSag.toFixed(2)} m</span>`,
      `+${(s.lowerLength - s.poleSpan).toFixed(2)} m`,
      `<span style="color:${statusColor(s.status)};font-weight:600;text-transform:uppercase;">${s.status}</span>`,
    ], i % 2 === 0),
  ]).join("");

  const body = `
    ${htmlHeader("Span Analysis Report", logo)}
    ${kpiGrid([
      { label: "Total Spans", value: String(NETWORK_SUMMARY.totalSpans) },
      { label: "Avg Sag", value: `${avgSag} m`, sub: "across 10 conductors" },
      { label: "Max Sag", value: `${maxSag} m`, sub: NETWORK_SUMMARY.maxSagSpan },
      { label: "Conductors", value: String(NETWORK_SUMMARY.totalConductors) },
    ])}
    ${sectionHeading("Span & Conductor Geometry")}
    ${table(
      tableHead("Conductor","Type","Pole Span","Wire Length","Sag","Expansion","Status"),
      spanRows
    )}
    ${sectionHeading("Sag Assessment")}
    <div style="background:#fdfefe;border:1px solid #d5d8dc;border-radius:8px;padding:16px;font-size:12px;line-height:2;">
      <strong style="color:#c0392b;">● Critical (&gt;2.0 m):</strong> Span 3–4 Lower (2.22 m) — Immediate retensioning required<br/>
      <strong style="color:#e67e22;">● Elevated (1.5–2.0 m):</strong> Spans 2–3 L, 5–6 L, 6–7 L — Monitor &amp; schedule maintenance<br/>
      <strong style="color:#27ae60;">● Normal (&lt;1.5 m):</strong> Spans 3–4 U, 4–5 U/L, 5–6 U, 6–7 U — No action required
    </div>
    ${htmlFooter()}`;

  printWindow(body, "Span_Analysis_Report");
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. SAG ANALYSIS REPORT
// ─────────────────────────────────────────────────────────────────────────────

export async function generateSagAnalysisReport() {
  const logo = await loadLogoDataUrl();

  const rows = CONDUCTORS.map((c, i) =>
    tableRow([
      `<strong>${c.id}</strong>`,
      `Span ${c.span}`,
      c.type,
      `${c.length.toFixed(2)} m`,
      `<span style="color:${sagColor(c.sag)};font-weight:700;">${c.sag.toFixed(2)} m</span>`,
      `<span style="color:${sagColor(c.sag)};font-weight:600;">${
        c.sag > 2 ? "CRITICAL" : c.sag > 1.5 ? "ELEVATED" : "NORMAL"
      }</span>`,
    ], i % 2 === 1)
  ).join("");

  const body = `
    ${htmlHeader("Conductor Sag Analysis Report", logo)}
    ${kpiGrid([
      { label: "Max Sag", value: `${NETWORK_SUMMARY.maxSag} m`, sub: NETWORK_SUMMARY.maxSagSpan },
      { label: "Avg Sag", value: `${NETWORK_SUMMARY.avgSag} m` },
      { label: "Critical Conductors", value: "1", sub: "> 2.0 m threshold" },
      { label: "Elevated Conductors", value: "3", sub: "1.5 – 2.0 m" },
    ])}
    ${sectionHeading("Sag Measurements per Conductor")}
    ${table(tableHead("Conductor","Span","Type","Wire Length","Sag","Assessment"), rows)}
    ${sectionHeading("Recommendations")}
    <div style="background:#fef9e7;border-left:4px solid #f39c12;padding:14px 16px;
                border-radius:0 8px 8px 0;font-size:12px;line-height:2;">
      <strong>Span 3–4 Lower Wire (Sag: 2.22 m)</strong><br/>
      • Immediate conductor retensioning required<br/>
      • Schedule inspection within 30 days<br/>
      • Review thermal expansion calculations<br/><br/>
      <strong>Spans with Elevated Sag (1.5 – 2.0 m)</strong><br/>
      • Monitor over next 90 days<br/>
      • Schedule maintenance during next planned outage<br/>
      • Document current measurements for trending analysis
    </div>
    ${htmlFooter()}`;

  printWindow(body, "Conductor_Sag_Report");
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. ENERGY LOSS REPORT
// ─────────────────────────────────────────────────────────────────────────────

export async function generateEnergyLossReport() {
  const logo = await loadLogoDataUrl();
  const sorted = [...CONDUCTORS].sort((a, b) => b.powerLoss - a.powerLoss);

  const rows = sorted.map((c, i) =>
    tableRow([
      `<strong style="color:#1a3a5c;">#${i + 1}</strong>`,
      `<strong>${c.id}</strong>`,
      `Span ${c.span}`,
      c.type,
      `${c.sag.toFixed(2)} m`,
      `<span style="color:${lossColor(c.powerLoss)};font-weight:700;">${c.powerLoss.toFixed(3)} W</span>`,
      `${c.energyWaste.toFixed(3)} kWh/yr`,
    ], i % 2 === 1)
  ).join("");

  const body = `
    ${htmlHeader("Energy Loss Analysis Report", logo)}
    ${kpiGrid([
      { label: "Total Power Loss", value: `${NETWORK_SUMMARY.totalPowerLoss} W`, sub: "all conductors" },
      { label: "Annual Energy Waste", value: `${NETWORK_SUMMARY.totalEnergyWaste} kWh`, sub: "per year" },
      { label: "Highest Loss", value: `${sorted[0].powerLoss.toFixed(3)} W`, sub: sorted[0].id },
      { label: "Highest Sag", value: `${NETWORK_SUMMARY.maxSag} m`, sub: NETWORK_SUMMARY.maxSagSpan },
    ])}
    ${sectionHeading("Conductor Loss Ranking (Highest → Lowest)")}
    ${table(
      tableHead("Rank","Conductor","Span","Type","Sag","Power Loss","Energy Waste/yr"),
      rows
    )}
    ${sectionHeading("Critical Findings")}
    <div style="background:#fdf2f2;border-left:4px solid #c0392b;padding:14px 16px;
                border-radius:0 8px 8px 0;font-size:12px;line-height:2;margin-bottom:12px;">
      <strong style="color:#c0392b;">Span 3–4 Lower Conductor — CRITICAL</strong><br/>
      • Sag: 2.22 m (highest in network) · Power Loss: 4.031 W · Energy Waste: 35.314 kWh/yr<br/>
      • Immediate retensioning recommended
    </div>
    <div style="background:#fef9e7;border-left:4px solid #e67e22;padding:14px 16px;
                border-radius:0 8px 8px 0;font-size:12px;line-height:2;">
      <strong style="color:#e67e22;">Span 2–3 Lower Conductor — WARNING</strong><br/>
      • Sag: 1.91 m · Power Loss: 2.531 W · Energy Waste: 22.174 kWh/yr<br/>
      • Schedule maintenance within 90 days
    </div>
    ${htmlFooter()}`;

  printWindow(body, "Energy_Loss_Report");
}

// ─────────────────────────────────────────────────────────────────────────────
// 5. NETWORK TOPOLOGY REPORT
// ─────────────────────────────────────────────────────────────────────────────

export async function generateNetworkTopologyReport() {
  const logo = await loadLogoDataUrl();

  const poleRows = POLES.map((p, i) =>
    tableRow([
      `<strong>Pole ${p.id}</strong>`,
      `${p.height.toFixed(2)} m`,
      `${p.x.toFixed(1)}`,
      `${p.y.toFixed(1)}`,
      "Class 18",
    ], i % 2 === 1)
  ).join("");

  const spanRows = SPANS.map((s, i) =>
    tableRow([
      `<strong>Span ${s.id}</strong>`,
      `Pole ${s.poleFrom}`,
      `Pole ${s.poleTo}`,
      `${s.poleSpan.toFixed(2)} m`,
      "2 conductors",
      `<span style="color:${statusColor(s.status)};font-weight:600;text-transform:uppercase;">${s.status}</span>`,
    ], i % 2 === 1)
  ).join("");

  const body = `
    ${htmlHeader("Network Topology Report", logo)}
    ${kpiGrid([
      { label: "Total Poles", value: String(NETWORK_SUMMARY.totalPoles) },
      { label: "Total Spans", value: String(NETWORK_SUMMARY.totalSpans) },
      { label: "Total Conductors", value: String(NETWORK_SUMMARY.totalConductors) },
      { label: "LiDAR Points", value: NETWORK_SUMMARY.totalPoints.toLocaleString() },
      { label: "Coverage Area", value: "0.99 ha" },
      { label: "Avg Pole Height", value: `${NETWORK_SUMMARY.avgPoleHeight} m` },
    ])}
    ${sectionHeading("Pole Locations & Heights")}
    ${table(tableHead("Pole ID","Height","X Coord","Y Coord","Class"), poleRows)}
    ${sectionHeading("Span Topology")}
    ${table(tableHead("Span ID","From Pole","To Pole","Distance","Conductors","Status"), spanRows)}
    ${sectionHeading("Dataset Information")}
    <div style="background:#eaf0fb;border:1px solid #aed6f1;border-radius:8px;
                padding:16px;font-size:12px;line-height:2.2;">
      <strong>File:</strong> ${DATASET_NAME} &nbsp;|&nbsp;
      <strong>Points:</strong> ${NETWORK_SUMMARY.totalPoints.toLocaleString()} &nbsp;|&nbsp;
      <strong>Classes:</strong> 5 ASPRS &nbsp;|&nbsp;
      <strong>Area:</strong> 0.99 ha<br/>
      <strong>Engine:</strong> ${ENGINE_VERSION} &nbsp;|&nbsp;
      <strong>Generated:</strong> ${nowString()}
    </div>
    ${htmlFooter()}`;

  printWindow(body, "Network_Topology_Report");
}

// ─────────────────────────────────────────────────────────────────────────────
// 6. FULL ENGINEERING SUMMARY REPORT
// ─────────────────────────────────────────────────────────────────────────────

export async function generateFullSummaryReport() {
  const logo = await loadLogoDataUrl();

  const poleRows = POLES.map((p, i) =>
    tableRow([
      `Pole ${p.id}`,
      `${p.height.toFixed(2)} m`,
      `${p.x.toFixed(1)}`,
      `${p.y.toFixed(1)}`,
    ], i % 2 === 1)
  ).join("");

  const conductorRows = CONDUCTORS.map((c, i) =>
    tableRow([
      c.id,
      `Span ${c.span}`,
      c.type,
      `${c.length.toFixed(2)} m`,
      `<span style="color:${sagColor(c.sag)};font-weight:600;">${c.sag.toFixed(2)} m</span>`,
      `<span style="color:${lossColor(c.powerLoss)};font-weight:600;">${c.powerLoss.toFixed(3)} W</span>`,
      `${c.energyWaste.toFixed(3)} kWh`,
    ], i % 2 === 1)
  ).join("");

  const body = `
    ${htmlHeader("Full Engineering Summary Report", logo)}

    <div style="background:#1a3a5c;color:white;border-radius:10px;padding:18px 20px;
                margin-bottom:20px;font-size:12px;line-height:2;">
      This report provides a comprehensive analysis of the powerline infrastructure
      surveyed via LiDAR point cloud technology. It covers pole inventory, span geometry,
      conductor sag analysis, and energy loss assessment across all detected spans.
    </div>

    ${kpiGrid([
      { label: "LiDAR Points", value: NETWORK_SUMMARY.totalPoints.toLocaleString() },
      { label: "Utility Poles", value: String(NETWORK_SUMMARY.totalPoles) },
      { label: "Spans", value: String(NETWORK_SUMMARY.totalSpans) },
      { label: "Conductors", value: String(NETWORK_SUMMARY.totalConductors) },
      { label: "Max Sag", value: `${NETWORK_SUMMARY.maxSag} m` },
      { label: "Total Power Loss", value: `${NETWORK_SUMMARY.totalPowerLoss} W` },
      { label: "Annual Energy Waste", value: `${NETWORK_SUMMARY.totalEnergyWaste} kWh` },
      { label: "Avg Pole Height", value: `${NETWORK_SUMMARY.avgPoleHeight} m` },
    ])}

    ${sectionHeading("Section 1 — Pole Inventory")}
    ${table(tableHead("Pole ID","Height","X Coord","Y Coord"), poleRows)}

    ${sectionHeading("Section 2 — Span & Conductor Analysis")}
    ${table(
      tableHead("Conductor","Span","Type","Wire Length","Sag","Power Loss","Energy Waste"),
      conductorRows
    )}

    ${sectionHeading("Section 3 — Critical Findings & Recommendations")}
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:16px;">
      <div style="background:#fdf2f2;border-left:4px solid #c0392b;padding:14px;
                  border-radius:0 8px 8px 0;font-size:12px;line-height:1.8;">
        <strong style="color:#c0392b;">CRITICAL — Span 3–4 Lower</strong><br/>
        Sag 2.22 m · Loss 4.031 W · 35.314 kWh/yr<br/>
        <em>Action: Immediate retensioning within 30 days</em>
      </div>
      <div style="background:#fef9e7;border-left:4px solid #e67e22;padding:14px;
                  border-radius:0 8px 8px 0;font-size:12px;line-height:1.8;">
        <strong style="color:#e67e22;">WARNING — Spans 2–3 L, 5–6 L, 6–7 L</strong><br/>
        Sag 1.80–1.91 m · Elevated loss values<br/>
        <em>Action: Schedule maintenance within 90 days</em>
      </div>
    </div>
    <div style="background:#eafaf1;border-left:4px solid #27ae60;padding:14px;
                border-radius:0 8px 8px 0;font-size:12px;line-height:1.8;">
      <strong style="color:#27ae60;">NORMAL — Spans 3–4 U, 4–5 U/L, 5–6 U, 6–7 U</strong><br/>
      All measurements within acceptable limits. Continue standard annual inspection schedule.
    </div>

    ${sectionHeading("Section 4 — Dataset & Engine Information")}
    <div style="background:#eaf0fb;border:1px solid #aed6f1;border-radius:8px;
                padding:16px;font-size:12px;line-height:2.2;">
      <strong>File:</strong> ${DATASET_NAME} &nbsp;·&nbsp;
      <strong>Info:</strong> ${DATASET_INFO}<br/>
      <strong>Engine:</strong> ${ENGINE_VERSION} &nbsp;·&nbsp;
      <strong>Generated:</strong> ${nowString()}
    </div>
    ${htmlFooter()}`;

  printWindow(body, "Full_Engineering_Summary_Report");
}

// ─────────────────────────────────────────────────────────────────────────────
// 7. TXT EXPORT (plain text, instant download)
// ─────────────────────────────────────────────────────────────────────────────

export function generateTxtReport(reportType: string): void {
  const ts = nowString();
  const line = "─".repeat(72);
  const dbl  = "═".repeat(72);

  let content = `${dbl}
  GridScan LiDAR Powerline Analytics Platform
  ${reportType}
  Dataset : ${DATASET_NAME}  |  ${DATASET_INFO}
  Engine  : ${ENGINE_VERSION}
  Generated: ${ts}
${dbl}

`;

  if (reportType.includes("Asset") || reportType.includes("Summary")) {
    content += `POLE INVENTORY\n${line}\n`;
    content += `${"Pole ID".padEnd(12)}${"Height (m)".padEnd(14)}${"X Coord".padEnd(14)}Y Coord\n`;
    content += `${line}\n`;
    POLES.forEach((p) => {
      content += `${"Pole " + p.id}`.padEnd(12) +
        `${p.height.toFixed(2)} m`.padEnd(14) +
        `${p.x.toFixed(1)}`.padEnd(14) +
        `${p.y.toFixed(1)}\n`;
    });
    content += "\n";
  }

  if (reportType.includes("Span") || reportType.includes("Sag") || reportType.includes("Summary")) {
    content += `SPAN & CONDUCTOR DATA\n${line}\n`;
    content += `${"Conductor".padEnd(12)}${"Type".padEnd(10)}${"Pole Span".padEnd(12)}${"Wire Len".padEnd(12)}${"Sag".padEnd(10)}Status\n`;
    content += `${line}\n`;
    SPANS.forEach((s) => {
      [
        { id: `${s.id} U`, type: "Upper", len: s.upperLength, sag: s.upperSag },
        { id: `${s.id} L`, type: "Lower", len: s.lowerLength, sag: s.lowerSag },
      ].forEach((c) => {
        const status = c.sag > 2 ? "CRITICAL" : c.sag > 1.5 ? "ELEVATED" : "Normal";
        content +=
          c.id.padEnd(12) +
          c.type.padEnd(10) +
          `${s.poleSpan.toFixed(2)} m`.padEnd(12) +
          `${c.len.toFixed(2)} m`.padEnd(12) +
          `${c.sag.toFixed(2)} m`.padEnd(10) +
          status + "\n";
      });
    });
    content += "\n";
  }

  if (reportType.includes("Energy") || reportType.includes("Summary")) {
    content += `ENERGY LOSS DATA\n${line}\n`;
    content += `${"Conductor".padEnd(12)}${"Type".padEnd(10)}${"Sag".padEnd(10)}${"Power Loss".padEnd(14)}Energy Waste/yr\n`;
    content += `${line}\n`;
    CONDUCTORS.forEach((c) => {
      content +=
        c.id.padEnd(12) +
        c.type.padEnd(10) +
        `${c.sag.toFixed(2)} m`.padEnd(10) +
        `${c.powerLoss.toFixed(3)} W`.padEnd(14) +
        `${c.energyWaste.toFixed(3)} kWh\n`;
    });
    content += `\n${"─".repeat(44)}\n`;
    content += `TOTAL POWER LOSS : ${NETWORK_SUMMARY.totalPowerLoss} W\n`;
    content += `TOTAL ENERGY WASTE: ${NETWORK_SUMMARY.totalEnergyWaste} kWh/year\n\n`;
  }

  content += `${dbl}\n`;
  content += `  Generated by GridScan LiDAR Powerline Analytics Platform\n`;
  content += `  CONFIDENTIAL ENGINEERING REPORT\n`;
  content += `${dbl}\n`;

  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  const filename = reportType.replace(/\s+/g, "_") + ".txt";
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
