/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewerRouteImport } from './routes/viewer'
import { Route as SpansRouteImport } from './routes/spans'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as EnergyRouteImport } from './routes/energy'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'

const ViewerRoute = ViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const SpansRoute = SpansRouteImport.update({
  id: '/spans',
  path: '/spans',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyRoute = EnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/energy': typeof EnergyRoute
  '/reports': typeof ReportsRoute
  '/spans': typeof SpansRoute
  '/viewer': typeof ViewerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/energy': typeof EnergyRoute
  '/reports': typeof ReportsRoute
  '/spans': typeof SpansRoute
  '/viewer': typeof ViewerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/energy': typeof EnergyRoute
  '/reports': typeof ReportsRoute
  '/spans': typeof SpansRoute
  '/viewer': typeof ViewerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assets' | '/energy' | '/reports' | '/spans' | '/viewer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assets' | '/energy' | '/reports' | '/spans' | '/viewer'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/energy'
    | '/reports'
    | '/spans'
    | '/viewer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  EnergyRoute: typeof EnergyRoute
  ReportsRoute: typeof ReportsRoute
  SpansRoute: typeof SpansRoute
  ViewerRoute: typeof ViewerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viewer': {
      id: '/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof ViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spans': {
      id: '/spans'
      path: '/spans'
      fullPath: '/spans'
      preLoaderRoute: typeof SpansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy': {
      id: '/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof EnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  EnergyRoute: EnergyRoute,
  ReportsRoute: ReportsRoute,
  SpansRoute: SpansRoute,
  ViewerRoute: ViewerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
